// ---------------------------------------------------------------------------
// Run this ONCE (and whenever you edit the knowledge base) to build the
// vector index Lumora retrieves from:
//
//     node scripts/embed.mjs
//
// It embeds every knowledge-base entry with OpenAI's embedding model and
// writes the vectors to src/lib/knowledgeIndex.json. That file is what the
// retriever loads at runtime — embeddings are computed once, not per request.
// ---------------------------------------------------------------------------

import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import OpenAI from "openai";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load the knowledge base. We read it as text and extract the array via a
// dynamic import using a tiny shim, so this script stays dependency-light.
const { KNOWLEDGE_BASE } = await import("../src/lib/knowledgeBase.js");

const EMBED_MODEL = "text-embedding-3-small";

async function main() {
  if (!process.env.OPENAI_API_KEY) {
    console.error(
      "\n✗ OPENAI_API_KEY not found. Make sure it's in .env.local, then run again.\n"
    );
    process.exit(1);
  }

  const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

  console.log(`\nEmbedding ${KNOWLEDGE_BASE.length} knowledge-base entries…`);

  const inputs = KNOWLEDGE_BASE.map((e) => `${e.title}\n\n${e.text}`);

  const res = await openai.embeddings.create({
    model: EMBED_MODEL,
    input: inputs,
  });

  const index = KNOWLEDGE_BASE.map((entry, i) => ({
    id: entry.id,
    title: entry.title,
    source: entry.source,
    text: entry.text,
    embedding: res.data[i].embedding,
  }));

  const outPath = path.join(__dirname, "..", "src", "lib", "knowledgeIndex.js");
  const fileBody =
    "// AUTO-GENERATED by scripts/embed.mjs — do not edit by hand.\n" +
    "// Run `npm run embed` to regenerate after editing the knowledge base.\n" +
    `export const EMBED_MODEL = ${JSON.stringify(EMBED_MODEL)};\n` +
    `export const INDEX = ${JSON.stringify(index)};\n`;
  fs.writeFileSync(outPath, fileBody);

  console.log(`✓ Wrote ${index.length} vectors to src/lib/knowledgeIndex.js`);
  console.log("  Lumora's tutor will now ground answers in these sources.\n");
}

main().catch((err) => {
  console.error("\n✗ Embedding failed:", err.message, "\n");
  process.exit(1);
});
